return {
	"https://github.com/catppuccin/nvim",
	"https://github.com/nvim-mini/mini.indentscope",
	"https://github.com/lukas-reineke/indent-blankline.nvim",
	"https://github.com/brenoprata10/nvim-highlight-colors",
	"https://github.com/nvim-tree/nvim-web-devicons",
	"https://github.com/MunifTanjim/nui.nvim",
	"https://github.com/nvim-lua/plenary.nvim",
	"https://github.com/neovim/nvim-lspconfig",
	"https://github.com/hrsh7th/nvim-cmp",
	"https://github.com/hrsh7th/cmp-nvim-lsp",
	"https://github.com/hrsh7th/cmp-buffer",
	"https://github.com/hrsh7th/cmp-path",
	"https://github.com/hrsh7th/cmp-cmdline",
	"https://github.com/hrsh7th/cmp-nvim-lsp-signature-help",
	"https://github.com/nvim-treesitter/nvim-treesitter",
	"https://github.com/stevearc/conform.nvim",
	"https://github.com/akinsho/toggleterm.nvim",
	"https://github.com/windwp/nvim-autopairs",
	"https://github.com/windwp/nvim-ts-autotag",
	"https://github.com/MeanderingProgrammer/render-markdown.nvim",
	"https://github.com/vyfor/cord.nvim",
	"https://git.barrettruth.com/barrettruth/live-server.nvim",
	"https://github.com/lewis6991/gitsigns.nvim",
	-- "https://github.com/vimpostor/vim-tpipeline",
	-- "https://github.com/akinsho/bufferline.nvim",
	-- "https://github.com/nvim-lualine/lualine.nvim",
	-- "https://github.com/nvim-neo-tree/neo-tree.nvim",
}
